name: fruitsapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.4
  dartz: ^0.10.1
  dots_indicator: ^3.0.0
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.0
  flutter_facebook_auth: ^7.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg_provider: ^1.0.7
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  go_router: ^14.7.2
  google_sign_in: ^6.2.2
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.5.1
  skeletonizer: ^1.4.3
  supabase_flutter: ^2.8.3
  svg_flutter: ^0.0.1
  widget_and_text_animator: ^1.1.5
  easy_refresh: ^3.4.0
  flutter_otp_text_field: ^1.5.1+1
  pin_code_fields: ^8.0.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/BoldIcons/
    - assets/images/Icons/
  fonts:
   - family: Cairo
     fonts:
       - asset: assets/fonts/Cairo-Regular.ttf
       - asset: assets/fonts/Cairo-Bold.ttf
         weight: 700
       - asset: assets/fonts/Cairo-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Cairo-Medium.ttf
         weight: 500  
flutter_intl:
  enabled: true
flutter_assets:
  assets_path: assets/images/
  output_path: lib/Core/utils/assets
  filename: picture_assets.dart
  classname: PictureAssets
  ignore_comments: true