// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHRitiS1wRhMFgp1QHgJlEa4OCEEMzzT0',
    appId: '1:1070533804858:web:8f814013d3490efed70603',
    messagingSenderId: '1070533804858',
    projectId: 'fruitshub-app-5cc83',
    authDomain: 'fruitshub-app-5cc83.firebaseapp.com',
    storageBucket: 'fruitshub-app-5cc83.firebasestorage.app',
    measurementId: 'G-E9H53226FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeHCbvjQsv70iewRGCoktlmwUcUh3xrS4',
    appId: '1:1070533804858:android:e6439e40fbec8d4dd70603',
    messagingSenderId: '1070533804858',
    projectId: 'fruitshub-app-5cc83',
    storageBucket: 'fruitshub-app-5cc83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdIhENqQgNG63LKQxupe6dpT0djs-8-eI',
    appId: '1:1070533804858:ios:d86bb5926ad8d166d70603',
    messagingSenderId: '1070533804858',
    projectId: 'fruitshub-app-5cc83',
    storageBucket: 'fruitshub-app-5cc83.firebasestorage.app',
    iosBundleId: 'com.example.fruitsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdIhENqQgNG63LKQxupe6dpT0djs-8-eI',
    appId: '1:1070533804858:ios:d86bb5926ad8d166d70603',
    messagingSenderId: '1070533804858',
    projectId: 'fruitshub-app-5cc83',
    storageBucket: 'fruitshub-app-5cc83.firebasestorage.app',
    iosBundleId: 'com.example.fruitsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHRitiS1wRhMFgp1QHgJlEa4OCEEMzzT0',
    appId: '1:1070533804858:web:f3c471addba4ae03d70603',
    messagingSenderId: '1070533804858',
    projectId: 'fruitshub-app-5cc83',
    authDomain: 'fruitshub-app-5cc83.firebaseapp.com',
    storageBucket: 'fruitshub-app-5cc83.firebasestorage.app',
    measurementId: 'G-Y5GTB6S8TD',
  );
}
