name: Build Flutter iOS IPA

on:
  push:
    branches: [ main ]  # Runs on push to main branch
  workflow_dispatch:    # Allows manual triggering

jobs:
  build:
    runs-on: macos-latest  # Uses a free macOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # or 'beta' if needed

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup

      - name: Build IPA
        run: |
          flutter pub get
          flutter build ipa --release
          
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.ipa
          path: build/ios/ipa/*.ipa
